import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

import { getPeople } from '../helpers'
import { ListPeopleCriteria, Person } from '../models'
import { useEffect, useState } from 'react'

export default function Home() {
  let [people, setPeople] = useState<Person[]>([]);

  useEffect(() => {
    let criteria: ListPeopleCriteria = {
      page: 1,
      per_page: 10
    }

    getPeople(criteria)
      .then((people: Person[]) => {
        setPeople(people)
      })
      .catch((e: string) => console.error(e))
  }, [people])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Listing People</h1>

        <ul>
          {people.map((person: Person) => (
            <li>
              <span>{person.id}</span>
              <span>{person.first_name + " " + person.last_name}</span>
            </li>
          ))}
        </ul>

      </main>
    </>
  )
}
